import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useClinic } from '../context/ClinicContext';
import { AppointmentStatus, VisitNote } from '../types';
import ChatbotAssistant from '../components/ChatbotAssistant';

// Declare jsPDF types for TypeScript since we are loading via CDN
declare global {
  interface Window {
    jspdf: any;
  }
}

const AppointmentDetails: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { getAppointment, updateStatus, saveVisitNote, doctor } = useClinic();
  
  const appointment = getAppointment(id || '');
  
  const [symptoms, setSymptoms] = useState('');
  const [diagnosis, setDiagnosis] = useState('');
  const [prescription, setPrescription] = useState('');
  const [saveStatus, setSaveStatus] = useState<string>('');

  // Load data ONLY when the appointment ID changes or if we are revisiting the page.
  // We do NOT include 'appointment' object in dependency array to prevent overwriting
  // unsaved form data when status changes (e.g. clicking 'Start Consult').
  useEffect(() => {
    if (appointment?.visitNotes) {
      setSymptoms(appointment.visitNotes.symptoms);
      setDiagnosis(appointment.visitNotes.diagnosis);
      setPrescription(appointment.visitNotes.prescription);
    } else if (appointment) {
      // Clear form if it's a new appointment without notes
      setSymptoms('');
      setDiagnosis('');
      setPrescription('');
    }
  }, [appointment?.id]);

  if (!appointment) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[50vh]">
        <div className="text-xl font-bold text-gray-800 mb-2">Appointment Not Found</div>
        <button onClick={() => navigate('/')} className="text-blue-600 hover:underline">
          Return to Dashboard
        </button>
      </div>
    );
  }

  const handleSave = () => {
    const note: VisitNote = {
      symptoms,
      diagnosis,
      prescription,
      timestamp: new Date().toISOString()
    };
    saveVisitNote(appointment.id, note);
    
    // Provide clear feedback
    const time = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    setSaveStatus(`Saved to Local Storage at ${time}`);
    
    // Optional: Auto-complete if in consult
    if (appointment.status === AppointmentStatus.IN_CONSULT) {
        const confirmDone = window.confirm("Notes saved. Mark patient as DONE?");
        if (confirmDone) updateStatus(appointment.id, AppointmentStatus.DONE);
    }
  };

  const handleDownloadPDF = () => {
    if (!window.jspdf) {
      alert("PDF library is loading, please try again in a moment.");
      return;
    }
    
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(41, 128, 185);
    doc.text("Clinic Prescription", 105, 20, null, null, "center");
    
    // Doctor Info
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Dr. ${doctor.name}`, 20, 40);
    doc.text(`${doctor.specialty}`, 20, 46);
    
    // Date
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 150, 40);

    // Line separator
    doc.setLineWidth(0.5);
    doc.line(20, 55, 190, 55);

    // Patient Info
    doc.setFontSize(14);
    doc.text("Patient Details", 20, 65);
    doc.setFontSize(12);
    doc.text(`Name: ${appointment.patientName}`, 20, 75);
    doc.text(`Phone: ${appointment.phone}`, 20, 82);
    doc.text(`Reason: ${appointment.reason}`, 20, 89);

    // Clinical Notes
    let yPos = 110;
    
    doc.setFontSize(14);
    doc.setTextColor(41, 128, 185);
    doc.text("Diagnosis & Symptoms", 20, yPos);
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const splitSymptoms = doc.splitTextToSize(`Symptoms: ${symptoms}`, 170);
    doc.text(splitSymptoms, 20, yPos + 10);
    yPos += 10 + (splitSymptoms.length * 7);

    const splitDiagnosis = doc.splitTextToSize(`Diagnosis: ${diagnosis}`, 170);
    doc.text(splitDiagnosis, 20, yPos);
    yPos += 10 + (splitDiagnosis.length * 7);

    // Prescription
    yPos += 10;
    doc.setFontSize(14);
    doc.setTextColor(41, 128, 185);
    doc.text("Rx (Prescription)", 20, yPos);
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    const splitRx = doc.splitTextToSize(prescription, 170);
    doc.text(splitRx, 20, yPos + 10);

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by DocQueue System", 105, 280, null, null, "center");

    doc.save(`Prescription-${appointment.patientName}.pdf`);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6 pb-24">
      {/* Header Info */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 flex flex-col md:flex-row justify-between md:items-center gap-4">
        <div>
          <div className="flex items-center gap-3">
            <h1 className="text-2xl font-bold text-gray-900">{appointment.patientName}</h1>
            <span className={`px-2 py-1 text-xs font-semibold rounded-full 
              ${appointment.status === AppointmentStatus.WAITING ? 'bg-yellow-100 text-yellow-800' : 
                appointment.status === AppointmentStatus.IN_CONSULT ? 'bg-blue-100 text-blue-800' : 
                'bg-green-100 text-green-800'}`}>
              {appointment.status.replace('_', ' ')}
            </span>
          </div>
          <p className="text-gray-500 mt-1"><i className="fa-solid fa-phone mr-2"></i>{appointment.phone}</p>
          <p className="text-gray-500"><i className="fa-solid fa-file-medical mr-2"></i>Reason: {appointment.reason}</p>
        </div>
        
        <div className="flex gap-2">
           {appointment.status !== AppointmentStatus.DONE && (
              <button 
                onClick={() => updateStatus(appointment.id, AppointmentStatus.DONE)}
                className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg font-medium transition-colors shadow-sm"
              >
                Mark Complete
              </button>
           )}
           {appointment.status === AppointmentStatus.WAITING && (
              <button 
                onClick={() => updateStatus(appointment.id, AppointmentStatus.IN_CONSULT)}
                className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-medium transition-colors shadow-sm"
              >
                Start Consult
              </button>
           )}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column: Form */}
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 relative">
            <h2 className="text-lg font-bold text-gray-900 mb-4 flex items-center justify-between">
              <span className="flex items-center"><i className="fa-solid fa-clipboard-check text-blue-500 mr-2"></i> Clinical Notes</span>
              {saveStatus && <span className="text-xs font-normal text-green-600 bg-green-50 px-2 py-1 rounded animate-fade-in"><i className="fa-solid fa-check mr-1"></i> {saveStatus}</span>}
            </h2>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Symptoms</label>
                <textarea
                  className="w-full border border-gray-300 rounded-lg p-3 focus:ring-2 focus:ring-blue-500 focus:outline-none"
                  rows={3}
                  value={symptoms}
                  onChange={e => setSymptoms(e.target.value)}
                  placeholder="Patient reported symptoms..."
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Diagnosis</label>
                <textarea
                  className="w-full border border-gray-300 rounded-lg p-3 focus:ring-2 focus:ring-blue-500 focus:outline-none"
                  rows={2}
                  value={diagnosis}
                  onChange={e => setDiagnosis(e.target.value)}
                  placeholder="Doctor's diagnosis..."
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Prescription (Rx)</label>
                <textarea
                  className="w-full border border-gray-300 rounded-lg p-3 focus:ring-2 focus:ring-blue-500 focus:outline-none font-mono text-sm"
                  rows={6}
                  value={prescription}
                  onChange={e => setPrescription(e.target.value)}
                  placeholder="Drug Name - Dosage - Frequency"
                />
              </div>

              <div className="pt-4 flex gap-3">
                <button 
                  onClick={handleSave}
                  className="flex-1 bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700 font-medium transition-colors shadow-sm flex justify-center items-center"
                >
                  <i className="fa-solid fa-save mr-2"></i> Save Notes
                </button>
                <button 
                  onClick={handleDownloadPDF}
                  className="flex-1 bg-gray-800 text-white py-2 px-4 rounded-lg hover:bg-gray-900 font-medium transition-colors shadow-sm flex justify-center items-center"
                >
                  <i className="fa-solid fa-file-pdf mr-2"></i> Download PDF
                </button>
              </div>
            </div>
          </div>

          {/* Read-Only Record Section (To verify what is saved) */}
          {appointment.visitNotes && (
            <div className="bg-gray-50 rounded-xl shadow-inner border border-gray-200 p-6">
              <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4">
                <i className="fa-solid fa-database mr-2"></i> Last Saved Record
              </h3>
              <div className="space-y-3 text-sm text-gray-700">
                <div>
                  <span className="font-semibold text-gray-900">Symptoms:</span>
                  <p className="mt-1 pl-3 border-l-2 border-gray-300">{appointment.visitNotes.symptoms || 'N/A'}</p>
                </div>
                <div>
                  <span className="font-semibold text-gray-900">Diagnosis:</span>
                  <p className="mt-1 pl-3 border-l-2 border-gray-300">{appointment.visitNotes.diagnosis || 'N/A'}</p>
                </div>
                <div>
                  <span className="font-semibold text-gray-900">Prescription:</span>
                  <pre className="mt-1 pl-3 border-l-2 border-gray-300 whitespace-pre-wrap font-mono text-xs">{appointment.visitNotes.prescription || 'N/A'}</pre>
                </div>
                <div className="text-xs text-gray-400 text-right mt-2">
                  Saved: {new Date(appointment.visitNotes.timestamp).toLocaleString()}
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Right Column: Tips & AI */}
        <div className="lg:col-span-1 space-y-6">
          <div className="bg-blue-50 border border-blue-100 rounded-xl p-6">
            <h3 className="font-bold text-blue-800 mb-2">Doctor's Quick Actions</h3>
            <ul className="space-y-2 text-sm text-blue-900">
              <li className="flex items-center gap-2">
                <i className="fa-solid fa-check text-blue-500"></i> Review previous history
              </li>
              <li className="flex items-center gap-2">
                <i className="fa-solid fa-check text-blue-500"></i> Check allergies
              </li>
              <li className="flex items-center gap-2">
                <i className="fa-solid fa-check text-blue-500"></i> Confirm next visit
              </li>
            </ul>
          </div>
          
          <div className="bg-purple-50 border border-purple-100 rounded-xl p-6">
             <h3 className="font-bold text-purple-800 mb-2">AI Assistant Active</h3>
             <p className="text-sm text-purple-900 mb-2">
               Use the chat bubble to analyze these symptoms or suggest treatments.
             </p>
             <div className="text-xs text-purple-700 bg-purple-100 p-2 rounded">
                <i className="fa-solid fa-lightbulb mr-1"></i> Tip: Try asking "Create a prescription for these symptoms".
             </div>
          </div>
        </div>
      </div>
      
      {/* Floating Chatbot */}
      <ChatbotAssistant 
        currentSymptoms={symptoms} 
        currentDiagnosis={diagnosis} 
      />
    </div>
  );
};

export default AppointmentDetails;